"""
Helper to get all fields about all tables.
"""

field_definitions: dict = {
    "feedback-table": {
        "all": {
            "id",
            "date_modified",
            "issue_date",
            "details_of_error",
            "location_of_error",
            "name_of_person",
            "name_of_city",
            "email_or_phone",
        },
        "required": {
            "id",
            "date_modified",
            "issue_date",
            "details_of_error",
            "location_of_error",
            "name_of_person",
            "name_of_city",
        },
        "key": "id",
    },
    "advertiser-table": {
        "all": {
            "email",
            "advert_type",
            "company_name",
            "contact_person_name",
            "phone_number",
            "web_site",
            "business_type",
            "ad_place_preference",
            "budget",
            "referred_by",
            "date_modified",
        },
        "required": {
            "email",
            "advert_type",
            "company_name",
            "contact_person_name",
            "phone_number",
            "business_type",
            "date_modified",
        },
        "key": "email",
    },
    "subscribe-table": {
        "all": {
            "date_modified",
            "email_address",
            "phone_number",
            "contact_preference",
            "full_name",
            "thirumaligai",
            "interests",
            "samashrayanam",
            "acharyan_name",
            "address_line_1",
            "address_line_2",
            "name_of_city",
            "postal_code",
            "state_or_province",
            "name_of_country",
            "authorise_to_contact",
        },
        "required": {
            "date_modified",
            "email_address",
            "phone_number",
            "contact_preference",
            "full_name",
            "samashrayanam",
            "address_line_1",
            "name_of_city",
            "postal_code",
            "state_or_province",
            "name_of_country",
            "authorise_to_contact",
        },
        "key": "phone_number",
    },
    "query-table": {
        "all": {
            "id",
            "date_modified",
            "query_topic",
            "question_asked",
            "name_of_person",
            "name_of_city",
            "email_or_phone",
        },
        "required": {
            "id",
            "date_modified",
            "query_topic",
            "question_asked",
            "name_of_person",
            "name_of_city",
        },
        "key": "id",
    },
}
